module.exports = {
  title: "Tutorials",
  tagline: "This code for this site was generated by Makersaurus",
  url: "https://example.h2o.ai",
  baseUrl: "/",
  projectName: "tutorials", // Usually your repo name
  feedbackAssignee: "5675sp", // Should be a github username
  dependencies: {
    "@emotion/react": "^11.10.5",
    "@emotion/styled": "^11.10.5",
    "@material-ui/core": "^4.12.4",
    "@material/card": "^14.0.0",
    "@mui/icons-material": "^5.10.16",
    "@mui/material": "^5.10.16",
    "react-player": "^2.11.0",
  },
};
